function  CompareMonthlyProfiles(month)

% crude script to compare the same month across years.
%
% USAGE (compare January of all years):
%    CompareMonthlyProfiles(1)

%% DART software - Copyright UCAR. This open source software is provided
% by UCAR, "as is", without charge, subject to all terms of use at
% http://www.image.ucar.edu/DAReS/DART/DART_download
%
% The obs_diag_output.nc files are archived in
% /glade/p/nsc/ncis0006/Reanalyses/f.e21.FHIST_BGC.f09_025.CAM6assim.011/ ...
%                esp/hist/YYYY-MM/Diags_NTrS_YYYY-MM.tgz
% /gpfs/csfs1/cisl/dares/Reanalyses/f.e21.FHIST_BGC.f09_025.CAM6assim.011/ ...
%                esp/hist/YYYY-MM/Diags_NTrS_YYYY-MM.tgz

% The first place they live is

DOUT_S_ROOT = '/glade/scratch/raeder/f.e21.FHIST_BGC.f09_025.CAM6assim.011/archive/esp/hist';

years   = 2010:2016;
nyears  = length(years);
files   = cell(1,nyears);
titiles = cell(1,nyears);
prpo    = 'prior';

for i = 1:nyears

   titles{1,i} = sprintf('%d-%02d',years(i),month);
   files{1,i}  = sprintf('%s/Diags_NTrS_%s/obs_diag_output.nc',DOUT_S_ROOT,titles{1,i});

end

obsnames = {  ...
        'ACARS_HORIZONTAL_WIND', ...
        'ACARS_TEMPERATURE', ...
        'ACARS_U_WIND_COMPONENT', ...
        'ACARS_V_WIND_COMPONENT', ...
        'AIRCRAFT_HORIZONTAL_WIND', ...
        'AIRCRAFT_TEMPERATURE', ...
        'AIRCRAFT_U_WIND_COMPONENT', ...
        'AIRCRAFT_V_WIND_COMPONENT', ...
        'AIRS_SPECIFIC_HUMIDITY', ...
        'AIRS_TEMPERATURE', ...
        'GPSRO_REFRACTIVITY', ...
        'RADIOSONDE_HORIZONTAL_WIND', ...
        'RADIOSONDE_SPECIFIC_HUMIDITY', ...
        'RADIOSONDE_TEMPERATURE', ...
        'RADIOSONDE_U_WIND_COMPONENT', ...
        'RADIOSONDE_V_WIND_COMPONENT', ...
        'SAT_HORIZONTAL_WIND', ...
        'SAT_U_WIND_COMPONENT', ...
        'SAT_V_WIND_COMPONENT'};

figure; set(gcf,'Position',[  20, 500,625,900])
figure; set(gcf,'Position',[ 660, 500,625,900])
figure; set(gcf,'Position',[1300, 500,625,900])

copy = 'rmse';
compare_monthly_profiles(files,titles,obsnames,copy,prpo,'MarkerSize',5,'LineWidth',1.5);

copy = 'bias';
compare_monthly_profiles(files,titles,obsnames,copy,prpo,'MarkerSize',5,'LineWidth',1.5);

copy = 'totalspread';
compare_monthly_profiles(files,titles,obsnames,copy,prpo,'MarkerSize',5,'LineWidth',1.5);
