#!/usr/bin/env bash

# DART software - Copyright UCAR. This open source software is provided
# by UCAR, "as is", without charge, subject to all terms of use at
# http://www.image.ucar.edu/DAReS/DART/DART_download

#-------------------------
# Auto-generate assim_model_mod.f90 for multiple models
# This creates a multi-model wrapper based on model_config.sh
#-------------------------

set -e

if [ $# -lt 1 ]; then
  echo "Usage: $0 <output_file>"
  echo "  output_file: path for generated assim_model_mod.f90"
  exit 1
fi

OUTPUT_FILE=$1

export DART=$(git rev-parse --show-toplevel)
XMODEL_DIR="$DART/models/xmodel/work"

# Load configuration
source "$XMODEL_DIR/model_config.sh"
setup_lags

echo "Generating assim_model_mod.f90 for models: ${MODELS[@]}"

# Standard model_mod interfaces that need to be wrapped
ROUTINES=(
  "get_model_size"
  "static_init_model"
  "get_state_meta_data"
  "shortest_time_between_assimilations"
  "init_conditions"
  "init_time"
  "adv_1step"
  "end_model"
  "pert_model_copies"
  "get_close_obs"
  "get_close_state"
  "convert_vertical_obs"
  "convert_vertical_state"
  "model_interpolate"
  "read_model_time"
  "write_model_time"
  "nc_write_model_atts"
)

#-------------------------
# Generate the file
#-------------------------

cat > "$OUTPUT_FILE" <<'EOF'
! DART software - Copyright UCAR. This open source software is provided
! by UCAR, "as is", without charge, subject to all terms of use at
! http://www.image.ucar.edu/DAReS/DART/DART_download

!> Multi-model version of assim_model_mod
!> This module wraps multiple model_mod modules to support 
!> assimilation with multiple models in a single executable.
!>
!> AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
!> Generated by generate_assim_model_mod.sh
!> Edit model_config.sh to change which models are included
!>
!> DOMAIN MANAGEMENT:
!> Each model can have one or more domains. After calling static_init_model
!> for each model, assim_model_mod tracks which domains belong to which model.
!> This allows write_model_time() to route to the correct model
!> based on the domain parameter.

module assim_model_mod

use    types_mod, only : r8, i8

use time_manager_mod, only : time_type,                                            &
                             operator(<), operator(>), operator(+), operator(-),   &
                             operator(/), operator(*), operator(==), operator(/=)

use ensemble_manager_mod, only : ensemble_type

use utilities_mod, only : error_handler, E_ERR, E_MSG

use location_mod, only : location_type

use state_structure_mod, only : get_num_domains

use obs_kind_mod, only : get_num_quantities, get_index_for_quantity

EOF

# Generate use statements for each model
echo "! Import the renamed model_mod modules" >> "$OUTPUT_FILE"
echo "! These are generated by preprocessing the original model_mod.f90 files" >> "$OUTPUT_FILE"

for model in "${MODELS[@]}"; do
  short_name="${MODEL_SHORT_NAMES[$model]}"
  
  cat >> "$OUTPUT_FILE" <<EOF
use ${short_name}_model_mod, only : &
EOF
  
  # Add renamed imports for each routine
  for i in "${!ROUTINES[@]}"; do
    routine="${ROUTINES[$i]}"
    if [ $i -eq $((${#ROUTINES[@]} - 1)) ]; then
      # Last one, no comma
      echo "    ${short_name}_${routine} => ${routine}" >> "$OUTPUT_FILE"
    else
      echo "    ${short_name}_${routine} => ${routine}, &" >> "$OUTPUT_FILE"
    fi
  done
  
  echo "" >> "$OUTPUT_FILE"
done

# Continue with the rest of the module
cat >> "$OUTPUT_FILE" <<'EOF'
implicit none
private

public :: static_init_assim_model, &
          end_assim_model, &
          get_initial_condition, &
          get_closest_state_time_to, &
          get_state_meta_data, &
          get_model_time_step, &
          get_model_size,  &
          adv_1step, &
          interpolate, &
          pert_model_copies, &
          get_close_obs, &
          get_close_state, &
          convert_vertical_obs, &
          convert_vertical_state, &
          read_model_time, &
          write_model_time, &
          nc_write_model_atts

! Ensure init code is called exactly once
logical :: module_initialized = .false.

! Model size tracking
integer :: num_models
integer, allocatable :: model_sizes(:)
integer, allocatable :: model_offsets(:)  ! Starting index for each model in state vector
integer :: total_model_size

! Model names for identification
character(len=32), allocatable :: model_names(:)

! Domain tracking - maps domain_id to model_idx
integer, parameter :: MAX_DOMAINS = 100
integer :: domain_to_model(MAX_DOMAINS)
integer :: num_domains
integer, allocatable :: model_domain_start(:)  ! First domain_id for each model
integer, allocatable :: model_domain_count(:)  ! Number of domains for each model

! QTY routing - maps observation quantity to model_idx for interpolate
integer, allocatable :: qty_to_model(:)
integer :: default_interp_model  ! Model index for unmapped quantities

! version controlled file description
character(len=*), parameter :: source   = 'xmodel/assim_model_mod.f90'

!-------------------------------------------------------------

contains

!======================================================================

subroutine static_init_assim_model()
!----------------------------------------------------------------------
! Initializes the multi-model assim_model
! Calls static_init_model for each component model
!----------------------------------------------------------------------

integer :: model_idx
! Track domains before and after each model initialization
integer :: domains_before, domains_after, domain_idx

! only execute this code once, even if called multiple times.
if (module_initialized) return

module_initialized = .true.

EOF

# Set number of models directly
cat >> "$OUTPUT_FILE" <<EOF
num_models = ${#MODELS[@]}
EOF

cat >> "$OUTPUT_FILE" <<'EOF'

if (num_models == 0) then
   call error_handler(E_ERR, 'static_init_assim_model', &
        'No models enabled', source)
endif

allocate(model_sizes(num_models))
allocate(model_offsets(num_models))
allocate(model_names(num_models))
allocate(model_domain_start(num_models))
allocate(model_domain_count(num_models))

! Initialize domain tracking
domain_to_model(:) = -1
num_domains = 0
model_domain_count(:) = 0

! Initialize each model and get its size
model_idx = 0
total_model_size = 0

EOF

for model in "${MODELS[@]}"; do
  short_name="${MODEL_SHORT_NAMES[$model]}"
  
  cat >> "$OUTPUT_FILE" <<EOF
model_idx = model_idx + 1
model_names(model_idx) = '${short_name}'

! Track domains before initialization
domains_before = get_num_domains()

call ${short_name}_static_init_model()

! Track domains after initialization
domains_after = get_num_domains()
model_domain_start(model_idx) = domains_before + 1
model_domain_count(model_idx) = domains_after - domains_before

! Automatically register domains to this model
do domain_idx = domains_before + 1, domains_after
   domain_to_model(domain_idx) = model_idx
   num_domains = max(num_domains, domain_idx)
   write(*, *) 'DEBUG: Registered domain', domain_idx, 'to model', model_idx, '(', trim(model_names(model_idx)), ')'
enddo

model_sizes(model_idx) = ${short_name}_get_model_size()
model_offsets(model_idx) = total_model_size + 1
total_model_size = total_model_size + model_sizes(model_idx)
write(*, *) 'Model ', model_idx, ': ', trim(model_names(model_idx)), &
            ' Size: ', model_sizes(model_idx), ' Offset: ', model_offsets(model_idx), &
            ' Domains: ', model_domain_count(model_idx), &
            ' (', model_domain_start(model_idx), '-', domains_after, ')'

EOF
done

cat >> "$OUTPUT_FILE" <<'EOF'
write(*, *) 'Multi-model initialization complete'
write(*, *) 'Number of models: ', num_models
write(*, *) 'Total state size: ', total_model_size
write(*, *) ''
write(*, *) '=== DOMAIN TO MODEL MAPPING ==='
do domain_idx = 1, num_domains
   if (domain_to_model(domain_idx) > 0) then
      write(*, *) 'Domain', domain_idx, '-> Model', domain_to_model(domain_idx), &
                  '(', trim(model_names(domain_to_model(domain_idx))), ')'
   endif
enddo
write(*, *) '==============================='
write(*, *) ''

! Initialize observation quantity routing for interpolate
call init_qty_routing()

end subroutine static_init_assim_model

!======================================================================

subroutine init_qty_routing()
!----------------------------------------------------------------------
! Initialize mapping from observation quantities to models
! Based on configuration from model_config.sh
!----------------------------------------------------------------------
integer :: num_qtys, qty_index, model_idx
integer :: i

num_qtys = get_num_quantities()
allocate(qty_to_model(num_qtys))

! Initialize all to default model
EOF

# Determine default model index
default_model_found=0
default_idx=1
for i in "${!MODELS[@]}"; do
  model="${MODELS[$i]}"
  short_name="${MODEL_SHORT_NAMES[$model]}"
  idx=$((i + 1))
  if [ "$short_name" == "$DEFAULT_INTERPOLATE_MODEL" ]; then
    default_model_found=1
    default_idx=$idx
    break
  fi
done

if [ $default_model_found -eq 0 ]; then
  echo "WARNING: DEFAULT_INTERPOLATE_MODEL '$DEFAULT_INTERPOLATE_MODEL' not found in MODELS"
  echo "         Using first model as default"
  default_idx=1
fi

cat >> "$OUTPUT_FILE" <<EOF
default_interp_model = ${default_idx}
qty_to_model(:) = default_interp_model

write(*, *) ''
write(*, *) '=== QUANTITY TO MODEL ROUTING ==='
write(*, *) 'Default interpolate model: ', trim(model_names(default_interp_model))
write(*, *) ''

EOF

# Generate qty mapping for each model
for model in "${MODELS[@]}"; do
  short_name="${MODEL_SHORT_NAMES[$model]}"
  qtys="${MODEL_QTYS[$short_name]}"
  
  if [ -z "$qtys" ]; then
    continue  # Skip models with no explicit QTYs
  fi
  
  # Get model index
  model_idx=0
  for i in "${!MODELS[@]}"; do
    if [ "${MODELS[$i]}" == "$model" ]; then
      model_idx=$((i + 1))
      break
    fi
  done
  
  cat >> "$OUTPUT_FILE" <<EOF
! Assign QTYs to model: ${short_name}
write(*, *) 'Model ${short_name} handles:'
EOF
  
  # Process each QTY for this model
  for qty in $qtys; do
    cat >> "$OUTPUT_FILE" <<EOF
qty_index = get_index_for_quantity('${qty}')
if (qty_index > 0 .and. qty_index <= num_qtys) then
   qty_to_model(qty_index) = ${model_idx}
   write(*, *) '  - ${qty}'
else
   call error_handler(E_MSG, 'init_qty_routing', &
        'Unknown QTY: ${qty}', source)
endif
EOF
  done
  
  cat >> "$OUTPUT_FILE" <<EOF

EOF
done

cat >> "$OUTPUT_FILE" <<'EOF'
write(*, *) '====================================='
write(*, *) ''

end subroutine init_qty_routing

!======================================================================

function get_model_size()
!----------------------------------------------------------------------
! Returns the size of the combined model state
!----------------------------------------------------------------------

integer :: get_model_size

get_model_size = total_model_size

end function get_model_size

!======================================================================

subroutine get_state_meta_data(index_in, location, var_type)
!----------------------------------------------------------------------
! Returns the location and type of a state variable
! Determines which model owns this index and calls appropriate routine
!----------------------------------------------------------------------

integer(i8),         intent(in)  :: index_in
type(location_type), intent(out) :: location
integer, optional,   intent(out) :: var_type

integer :: model_idx, i

! Find which model owns this state index
model_idx = -1
do i = 1, num_models
   if (index_in >= model_offsets(i) .and. &
       index_in < model_offsets(i) + model_sizes(i)) then
      model_idx = i
      exit
   endif
enddo

if (model_idx == -1) then
   call error_handler(E_ERR, 'get_state_meta_data', &
        'Index not found in any model', source)
endif

! Call the appropriate model's get_state_meta_data based on model_idx
EOF

# Generate if-then-else for get_state_meta_data using integer comparison
model_count=0
for model in "${MODELS[@]}"; do
  model_count=$((model_count + 1))
  short_name="${MODEL_SHORT_NAMES[$model]}"
  
  if [ $model_count -eq 1 ]; then
    cat >> "$OUTPUT_FILE" <<EOF
if (model_idx == ${model_count}) then
   call ${short_name}_get_state_meta_data(index_in, location, var_type)
EOF
  else
    cat >> "$OUTPUT_FILE" <<EOF
else if (model_idx == ${model_count}) then
   call ${short_name}_get_state_meta_data(index_in, location, var_type)
EOF
  fi
done

cat >> "$OUTPUT_FILE" <<'EOF'
else
   call error_handler(E_ERR, 'get_state_meta_data', &
        'Invalid model_idx', source)
endif

end subroutine get_state_meta_data

!======================================================================

function get_model_time_step()
!----------------------------------------------------------------------
! Returns the shortest time step from all models
!----------------------------------------------------------------------

type(time_type) :: get_model_time_step
type(time_type) :: model_time_step
logical :: first_model

first_model = .true.

EOF

# Generate time step comparison
for model in "${MODELS[@]}"; do
  short_name="${MODEL_SHORT_NAMES[$model]}"
  
  cat >> "$OUTPUT_FILE" <<EOF
model_time_step = ${short_name}_shortest_time_between_assimilations()
if (first_model) then
   get_model_time_step = model_time_step
   first_model = .false.
else if (model_time_step < get_model_time_step) then
   get_model_time_step = model_time_step
endif

EOF
done

cat >> "$OUTPUT_FILE" <<'EOF'
end function get_model_time_step

!======================================================================

function get_closest_state_time_to(model_time, given_time)
!----------------------------------------------------------------------
! Returns the time closest to the given time that the model can reach
!----------------------------------------------------------------------

type(time_type) :: get_closest_state_time_to
type(time_type), intent(in) :: model_time, given_time

type(time_type) :: time_step

time_step = get_model_time_step()

if(model_time > given_time) then
   get_closest_state_time_to = model_time
   return
endif

get_closest_state_time_to = model_time

do while((time_step + 2*get_closest_state_time_to) < 2*given_time)
   get_closest_state_time_to = get_closest_state_time_to + time_step
enddo

end function get_closest_state_time_to

!======================================================================

subroutine get_initial_condition(initial_time, x)
!----------------------------------------------------------------------
! Get initial conditions for all models
!----------------------------------------------------------------------

type(time_type), intent(out) :: initial_time
real(r8),        intent(out) :: x(:)

integer :: model_idx, start_idx, end_idx
logical :: time_set

time_set = .false.

do model_idx = 1, num_models
   start_idx = model_offsets(model_idx)
   end_idx = start_idx + model_sizes(model_idx) - 1
   
EOF

# Generate init conditions for each model using integer comparison
model_count=0
for model in "${MODELS[@]}"; do
  model_count=$((model_count + 1))
  short_name="${MODEL_SHORT_NAMES[$model]}"
  
  if [ $model_count -eq 1 ]; then
    cat >> "$OUTPUT_FILE" <<EOF
   if (model_idx == ${model_count}) then
      call ${short_name}_init_conditions(x(start_idx:end_idx))
      if (.not. time_set) then
         call ${short_name}_init_time(initial_time)
         time_set = .true.
      endif
EOF
  else
    cat >> "$OUTPUT_FILE" <<EOF
   else if (model_idx == ${model_count}) then
      call ${short_name}_init_conditions(x(start_idx:end_idx))
      if (.not. time_set) then
         call ${short_name}_init_time(initial_time)
         time_set = .true.
      endif
EOF
  fi
done

cat >> "$OUTPUT_FILE" <<'EOF'
   endif
enddo

end subroutine get_initial_condition

!======================================================================

subroutine end_assim_model()
!--------------------------------------------------------------------
! Closes down assim_model - calls end_model for each component
!--------------------------------------------------------------------

EOF

# Generate end_model calls
for model in "${MODELS[@]}"; do
  short_name="${MODEL_SHORT_NAMES[$model]}"
  cat >> "$OUTPUT_FILE" <<EOF
call ${short_name}_end_model()
EOF
done

cat >> "$OUTPUT_FILE" <<'EOF'

end subroutine end_assim_model

!======================================================================
! Stub implementations for routines that need more complex handling
! These are placeholders that should be expanded based on requirements
!======================================================================

subroutine adv_1step(x, time)
!----------------------------------------------------------------------
real(r8),        intent(inout) :: x(:)
type(time_type), intent(in)    :: time

call error_handler(E_ERR, 'adv_1step', &
     'Multi-model advance not yet implemented', source)

end subroutine adv_1step

!======================================================================

subroutine interpolate(state_handle, ens_size, location, qty, expected_obs, istatus)
!----------------------------------------------------------------------
use ensemble_manager_mod, only : ensemble_type
integer,             intent(in) :: ens_size
type(ensemble_type), intent(in) :: state_handle
type(location_type), intent(in) :: location
integer,             intent(in) :: qty
real(r8),           intent(out) :: expected_obs(ens_size)
integer,            intent(out) :: istatus(ens_size)

integer :: model_idx
integer :: num_qtys

num_qtys = get_num_quantities()

! Determine which model should handle this quantity
if (qty < 1 .or. qty > num_qtys) then
   call error_handler(E_ERR, 'interpolate', 'Invalid quantity index', source)
endif

model_idx = qty_to_model(qty)

if (model_idx < 1 .or. model_idx > num_models) then
   call error_handler(E_ERR, 'interpolate', 'Invalid model_idx from qty routing', source)
endif

! Route to the appropriate model's interpolate
EOF

# Generate routing based on model_idx
model_count=0
for model in "${MODELS[@]}"; do
  model_count=$((model_count + 1))
  short_name="${MODEL_SHORT_NAMES[$model]}"
  
  if [ $model_count -eq 1 ]; then
    cat >> "$OUTPUT_FILE" <<EOF
if (model_idx == ${model_count}) then
   call ${short_name}_model_interpolate(state_handle, ens_size, location, qty, expected_obs, istatus)
EOF
  else
    cat >> "$OUTPUT_FILE" <<EOF
else if (model_idx == ${model_count}) then
   call ${short_name}_model_interpolate(state_handle, ens_size, location, qty, expected_obs, istatus)
EOF
  fi
done

cat >> "$OUTPUT_FILE" <<'EOF'
else
   call error_handler(E_ERR, 'interpolate', 'Invalid model_idx', source)
endif

end subroutine interpolate

!======================================================================

subroutine pert_model_copies(state_ens_handle, ens_size, pert_amp, interf_provided)
!----------------------------------------------------------------------  
use ensemble_manager_mod, only : ensemble_type
type(ensemble_type), intent(inout) :: state_ens_handle
integer,             intent(in)    :: ens_size
real(r8),            intent(in)    :: pert_amp
logical,             intent(out)   :: interf_provided

call error_handler(E_ERR, 'pert_model_copies', &
     'Multi-model perturbation not yet implemented', source)

end subroutine pert_model_copies

!======================================================================

subroutine get_close_obs(gc, base_loc, base_type, locs, qtys, types, num_close, &
                         close_ind, distances, state_handle)
!----------------------------------------------------------------------
use location_mod, only : get_close_type
use ensemble_manager_mod, only : ensemble_type

type(get_close_type),          intent(in)    :: gc
type(location_type),           intent(inout) :: base_loc
integer,                       intent(in)    :: base_type
type(location_type),           intent(inout) :: locs(:)
integer,                       intent(in)    :: qtys(:)
integer,                       intent(in)    :: types(:)
integer,                       intent(out)   :: num_close
integer,                       intent(out)   :: close_ind(:)
real(r8),            optional, intent(out)   :: distances(:)
type(ensemble_type), optional, intent(in)    :: state_handle

call error_handler(E_ERR, 'get_close_obs', &
     'Multi-model get_close_obs not yet implemented', source)

end subroutine get_close_obs

!======================================================================

subroutine get_close_state(gc, base_loc, base_type, locs, qtys, indx, num_close, &
                          close_ind, distances, state_handle)
!----------------------------------------------------------------------
use location_mod, only : get_close_type
use ensemble_manager_mod, only : ensemble_type

type(get_close_type),          intent(in)    :: gc
type(location_type),           intent(inout) :: base_loc
integer,                       intent(in)    :: base_type
type(location_type),           intent(inout) :: locs(:)
integer,                       intent(in)    :: qtys(:)
integer(i8),                   intent(in)    :: indx(:)
integer,                       intent(out)   :: num_close
integer,                       intent(out)   :: close_ind(:)
real(r8),            optional, intent(out)   :: distances(:)
type(ensemble_type), optional, intent(in)    :: state_handle

call error_handler(E_ERR, 'get_close_state', &
     'Multi-model get_close_state not yet implemented', source)

! todo, the indexes will be the same for each lag. 

end subroutine get_close_state

!======================================================================

subroutine convert_vertical_obs(ens_handle, num, locs, loc_qtys, loc_types, &
                                which_vert, status)
!----------------------------------------------------------------------
use ensemble_manager_mod, only : ensemble_type
type(ensemble_type), intent(in)    :: ens_handle
integer,             intent(in)    :: num
type(location_type), intent(inout) :: locs(:)
integer,             intent(in)    :: loc_qtys(:)
integer,             intent(in)    :: loc_types(:)
integer,             intent(in)    :: which_vert
integer,             intent(out)   :: status(:)

call error_handler(E_ERR, 'convert_vertical_obs', &
     'Multi-model vertical conversion not yet implemented', source)

end subroutine convert_vertical_obs

!======================================================================

subroutine convert_vertical_state(ens_handle, num, locs, loc_qtys, loc_indx, &
                                  which_vert, status)
!----------------------------------------------------------------------
use ensemble_manager_mod, only : ensemble_type
type(ensemble_type), intent(in)    :: ens_handle
integer,             intent(in)    :: num
type(location_type), intent(inout) :: locs(num)
integer,             intent(in)    :: loc_qtys(num)
integer(i8),         intent(in)    :: loc_indx(num)
integer,             intent(in)    :: which_vert
integer,             intent(out)   :: status

call error_handler(E_ERR, 'convert_vertical_state', &
     'Multi-model vertical conversion not yet implemented', source)

end subroutine convert_vertical_state

!======================================================================

function read_model_time(filename)
!----------------------------------------------------------------------
character(len=*),  intent(in)  :: filename
type(time_type)                :: read_model_time

EOF

# Use first model for read_model_time
first_model="${MODELS[0]}"
short_name="${MODEL_SHORT_NAMES[$first_model]}"
cat >> "$OUTPUT_FILE" <<EOF
! Use first model (${first_model}) for read_model_time
read_model_time = ${short_name}_read_model_time(filename)
EOF

cat >> "$OUTPUT_FILE" <<'EOF'

end function read_model_time

!======================================================================

subroutine write_model_time(ncid, model_time, domain_id)
!----------------------------------------------------------------------
integer,         intent(in) :: ncid
type(time_type), intent(in) :: model_time
integer, optional, intent(in) :: domain_id

integer :: model_idx

if (.not. present(domain_id)) then
   ! No domain specified - use first model (single domain case)
   print*, 'HELEN No domain_id provided to write_model_time - using first model by default'
EOF

# Use first model as default
first_model="${MODELS[0]}"
short_name="${MODEL_SHORT_NAMES[$first_model]}"
cat >> "$OUTPUT_FILE" <<EOF
   call ${short_name}_write_model_time(ncid, model_time)
EOF

cat >> "$OUTPUT_FILE" <<'EOF'
else
   ! Look up which model owns this domain
   if (domain_id < 1 .or. domain_id > MAX_DOMAINS) then
      call error_handler(E_ERR, 'write_model_time', 'Invalid domain_id', source)
   endif
   
   model_idx = domain_to_model(domain_id)
   write(*, *) 'DEBUG write_model_time: domain_id =', domain_id, 'maps to model_idx =', model_idx
   
   if (model_idx < 1 .or. model_idx > num_models) then
      write(*, *) 'ERROR: model_idx out of range. num_models =', num_models
      call error_handler(E_ERR, 'write_model_time', 'Domain not registered to any model', source)
   endif
   
   write(*, *) 'DEBUG: Calling write_model_time for model:', trim(model_names(model_idx))
   
   ! Call the appropriate model's write_model_time based on model_idx
EOF

# Generate routing based on model_idx using integer comparison
model_count=0
for model in "${MODELS[@]}"; do
  model_count=$((model_count + 1))
  short_name="${MODEL_SHORT_NAMES[$model]}"
  
  if [ $model_count -eq 1 ]; then
    cat >> "$OUTPUT_FILE" <<EOF
   if (model_idx == ${model_count}) then
      call ${short_name}_write_model_time(ncid, model_time)
EOF
  else
    cat >> "$OUTPUT_FILE" <<EOF
   else if (model_idx == ${model_count}) then
      call ${short_name}_write_model_time(ncid, model_time)
EOF
  fi
done

cat >> "$OUTPUT_FILE" <<'EOF'
   else
      call error_handler(E_ERR, 'write_model_time', 'Invalid model_idx', source)
   endif
endif

end subroutine write_model_time

!======================================================================

subroutine nc_write_model_atts(ncid, domain_id)
!----------------------------------------------------------------------
integer, intent(in) :: ncid
integer, intent(in) :: domain_id

integer :: model_idx

! Look up which model owns this domain
if (domain_id < 1 .or. domain_id > MAX_DOMAINS) then
   call error_handler(E_ERR, 'nc_write_model_atts', 'Invalid domain_id', source)
endif

model_idx = domain_to_model(domain_id)
write(*, *) 'DEBUG nc_write_model_atts: domain_id =', domain_id, 'maps to model_idx =', model_idx

if (model_idx < 1 .or. model_idx > num_models) then
   write(*, *) 'ERROR: model_idx out of range. num_models =', num_models
   call error_handler(E_ERR, 'nc_write_model_atts', 'Domain not registered to any model', source)
endif

write(*, *) 'DEBUG: Calling nc_write_model_atts for model:', trim(model_names(model_idx))

! Call the appropriate model's nc_write_model_atts based on model_idx
EOF

# Generate routing based on model_idx using integer comparison
model_count=0
for model in "${MODELS[@]}"; do
  model_count=$((model_count + 1))
  short_name="${MODEL_SHORT_NAMES[$model]}"
  
  if [ $model_count -eq 1 ]; then
    cat >> "$OUTPUT_FILE" <<EOF
if (model_idx == ${model_count}) then
   call ${short_name}_nc_write_model_atts(ncid, domain_id)
EOF
  else
    cat >> "$OUTPUT_FILE" <<EOF
else if (model_idx == ${model_count}) then
   call ${short_name}_nc_write_model_atts(ncid, domain_id)
EOF
  fi
done

cat >> "$OUTPUT_FILE" <<'EOF'
else
   call error_handler(E_ERR, 'nc_write_model_atts', 'Invalid model_idx', source)
endif

end subroutine nc_write_model_atts

!======================================================================

end module assim_model_mod
EOF

echo "Generated $OUTPUT_FILE"
