#!/usr/bin/env bash

# DART software - Copyright UCAR. This open source software is provided
# by UCAR, "as is", without charge, subject to all terms of use at
# http://www.image.ucar.edu/DAReS/DART/DART_download

#-------------------------
# Auto-generate assim_model_mod.f90 for multiple models
# This creates a multi-model wrapper based on model_config.sh
#-------------------------

set -e

if [ $# -lt 1 ]; then
  echo "Usage: $0 <output_file>"
  echo "  output_file: path for generated assim_model_mod.f90"
  exit 1
fi

OUTPUT_FILE=$1

export DART=$(git rev-parse --show-toplevel)
XMODEL_DIR="$DART/models/xmodel/work"

# Load configuration
source "$XMODEL_DIR/model_config.sh"

echo "Generating assim_model_mod.f90 for models: ${MODELS[@]}"

# Standard model_mod interfaces that need to be wrapped
ROUTINES=(
  "get_model_size"
  "static_init_model"
  "get_state_meta_data"
  "shortest_time_between_assimilations"
  "init_conditions"
  "init_time"
  "adv_1step"
  "end_model"
  "pert_model_copies"
  "get_close_obs"
  "get_close_state"
  "convert_vertical_obs"
  "convert_vertical_state"
  "model_interpolate"
  "read_model_time"
  "write_model_time"
)

#-------------------------
# Generate the file
#-------------------------

cat > "$OUTPUT_FILE" <<'EOF'
! DART software - Copyright UCAR. This open source software is provided
! by UCAR, "as is", without charge, subject to all terms of use at
! http://www.image.ucar.edu/DAReS/DART/DART_download

!> Multi-model version of assim_model_mod
!> This module wraps multiple model_mod modules to support 
!> assimilation with multiple models in a single executable.
!>
!> AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
!> Generated by generate_assim_model_mod.sh
!> Edit model_config.sh to change which models are included

module assim_model_mod

use    types_mod, only : r8, i8

use time_manager_mod, only : time_type,                                            &
                             operator(<), operator(>), operator(+), operator(-),   &
                             operator(/), operator(*), operator(==), operator(/=)

use ensemble_manager_mod, only : ensemble_type

use utilities_mod, only : register_module, error_handler, E_ERR, E_MSG

use location_mod, only : location_type

EOF

# Generate use statements for each model
echo "! Import the renamed model_mod modules" >> "$OUTPUT_FILE"
echo "! These are generated by preprocessing the original model_mod.f90 files" >> "$OUTPUT_FILE"

model_idx=0
for model in "${MODELS[@]}"; do
  model_idx=$((model_idx + 1))
  short_name="${MODEL_SHORT_NAMES[$model]}"
  flag=$(echo "$short_name" | tr '[:lower:]' '[:upper:]')
  
  cat >> "$OUTPUT_FILE" <<EOF
#ifdef USE_${flag}
use ${short_name}_model_mod, only : &
EOF
  
  # Add renamed imports for each routine
  for i in "${!ROUTINES[@]}"; do
    routine="${ROUTINES[$i]}"
    if [ $i -eq $((${#ROUTINES[@]} - 1)) ]; then
      # Last one, no comma
      echo "    ${short_name}_${routine} => ${routine}" >> "$OUTPUT_FILE"
    else
      echo "    ${short_name}_${routine} => ${routine}, &" >> "$OUTPUT_FILE"
    fi
  done
  
  echo "#endif" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"
done

# Continue with the rest of the module
cat >> "$OUTPUT_FILE" <<'EOF'
implicit none
private

public :: static_init_assim_model, &
          end_assim_model, &
          get_initial_condition, &
          get_closest_state_time_to, &
          get_state_meta_data, &
          get_model_time_step, &
          get_model_size,  &
          adv_1step, &
          interpolate, &
          pert_model_copies, &
          get_close_obs, &
          get_close_state, &
          convert_vertical_obs, &
          convert_vertical_state, &
          read_model_time, &
          write_model_time

! Ensure init code is called exactly once
logical :: module_initialized = .false.

! Model size tracking
integer :: num_models
integer, allocatable :: model_sizes(:)
integer, allocatable :: model_offsets(:)  ! Starting index for each model in state vector
integer :: total_model_size

! Model names for identification
character(len=32), allocatable :: model_names(:)

! version controlled file description
character(len=*), parameter :: source   = 'xmodel/assim_model_mod.f90'
character(len=*), parameter :: revision = ''
character(len=*), parameter :: revdate  = ''

!-------------------------------------------------------------

contains

!======================================================================

subroutine static_init_assim_model()
!----------------------------------------------------------------------
! Initializes the multi-model assim_model
! Calls static_init_model for each component model
!----------------------------------------------------------------------

integer :: model_idx

! only execute this code once, even if called multiple times.
if (module_initialized) return

call register_module(source, revision, revdate)

module_initialized = .true.

! Count how many models are enabled
num_models = 0
EOF

# Add model counting
for model in "${MODELS[@]}"; do
  short_name="${MODEL_SHORT_NAMES[$model]}"
  flag=$(echo "$short_name" | tr '[:lower:]' '[:upper:]')
  cat >> "$OUTPUT_FILE" <<EOF
#ifdef USE_${flag}
num_models = num_models + 1
#endif
EOF
done

cat >> "$OUTPUT_FILE" <<'EOF'

if (num_models == 0) then
   call error_handler(E_ERR, 'static_init_assim_model', &
        'No models enabled. Define at least one USE_* preprocessor flag', &
        source, revision, revdate)
endif

allocate(model_sizes(num_models))
allocate(model_offsets(num_models))
allocate(model_names(num_models))

! Initialize each model and get its size
model_idx = 0
total_model_size = 0

EOF

# Add initialization for each model
for model in "${MODELS[@]}"; do
  short_name="${MODEL_SHORT_NAMES[$model]}"
  flag=$(echo "$short_name" | tr '[:lower:]' '[:upper:]')
  cat >> "$OUTPUT_FILE" <<EOF
#ifdef USE_${flag}
model_idx = model_idx + 1
model_names(model_idx) = '${short_name}'
call ${short_name}_static_init_model()
model_sizes(model_idx) = ${short_name}_get_model_size()
model_offsets(model_idx) = total_model_size + 1
total_model_size = total_model_size + model_sizes(model_idx)
write(*, *) 'Model ', model_idx, ': ', trim(model_names(model_idx)), &
            ' Size: ', model_sizes(model_idx), ' Offset: ', model_offsets(model_idx)
#endif
EOF
done

cat >> "$OUTPUT_FILE" <<'EOF'

write(*, *) 'Multi-model initialization complete'
write(*, *) 'Number of models: ', num_models
write(*, *) 'Total state size: ', total_model_size

end subroutine static_init_assim_model

!======================================================================

function get_model_size()
!----------------------------------------------------------------------
! Returns the size of the combined model state
!----------------------------------------------------------------------

integer :: get_model_size

get_model_size = total_model_size

end function get_model_size

!======================================================================

subroutine get_state_meta_data(index_in, location, var_type)
!----------------------------------------------------------------------
! Returns the location and type of a state variable
! Determines which model owns this index and calls appropriate routine
!----------------------------------------------------------------------

integer(i8),         intent(in)  :: index_in
type(location_type), intent(out) :: location
integer, optional,   intent(out) :: var_type

integer :: model_idx, i
integer(i8) :: local_index

! Find which model owns this state index
model_idx = -1
do i = 1, num_models
   if (index_in >= model_offsets(i) .and. &
       index_in < model_offsets(i) + model_sizes(i)) then
      model_idx = i
      local_index = index_in - model_offsets(i) + 1
      exit
   endif
enddo

if (model_idx == -1) then
   call error_handler(E_ERR, 'get_state_meta_data', &
        'Index not found in any model', source, revision, revdate)
endif

! Call the appropriate model's get_state_meta_data based on model name
EOF

# Generate select for get_state_meta_data
first_model=1
for model in "${MODELS[@]}"; do
  short_name="${MODEL_SHORT_NAMES[$model]}"
  flag=$(echo "$short_name" | tr '[:lower:]' '[:upper:]')
  
  cat >> "$OUTPUT_FILE" <<EOF
#ifdef USE_${flag}
if (trim(model_names(model_idx)) == '${short_name}') then
   call ${short_name}_get_state_meta_data(local_index, location, var_type)
   return
endif
#endif
EOF
done

cat >> "$OUTPUT_FILE" <<'EOF'

call error_handler(E_ERR, 'get_state_meta_data', &
     'Unknown model name', source, revision, revdate)

end subroutine get_state_meta_data

!======================================================================

function get_model_time_step()
!----------------------------------------------------------------------
! Returns the shortest time step from all models
!----------------------------------------------------------------------

type(time_type) :: get_model_time_step
type(time_type) :: model_time_step
logical :: first_model

first_model = .true.

EOF

# Generate time step comparison
for model in "${MODELS[@]}"; do
  short_name="${MODEL_SHORT_NAMES[$model]}"
  flag=$(echo "$short_name" | tr '[:lower:]' '[:upper:]')
  
  cat >> "$OUTPUT_FILE" <<EOF
#ifdef USE_${flag}
model_time_step = ${short_name}_shortest_time_between_assimilations()
if (first_model) then
   get_model_time_step = model_time_step
   first_model = .false.
else if (model_time_step < get_model_time_step) then
   get_model_time_step = model_time_step
endif
#endif
EOF
done

cat >> "$OUTPUT_FILE" <<'EOF'

end function get_model_time_step

!======================================================================

function get_closest_state_time_to(model_time, given_time)
!----------------------------------------------------------------------
! Returns the time closest to the given time that the model can reach
!----------------------------------------------------------------------

type(time_type) :: get_closest_state_time_to
type(time_type), intent(in) :: model_time, given_time

type(time_type) :: time_step

time_step = get_model_time_step()

if(model_time > given_time) then
   get_closest_state_time_to = model_time
   return
endif

get_closest_state_time_to = model_time

do while((time_step + 2*get_closest_state_time_to) < 2*given_time)
   get_closest_state_time_to = get_closest_state_time_to + time_step
enddo

end function get_closest_state_time_to

!======================================================================

subroutine get_initial_condition(initial_time, x)
!----------------------------------------------------------------------
! Get initial conditions for all models
!----------------------------------------------------------------------

type(time_type), intent(out) :: initial_time
real(r8),        intent(out) :: x(:)

integer :: model_idx, start_idx, end_idx
logical :: time_set

time_set = .false.

do model_idx = 1, num_models
   start_idx = model_offsets(model_idx)
   end_idx = start_idx + model_sizes(model_idx) - 1
   
EOF

# Generate init conditions for each model
for model in "${MODELS[@]}"; do
  short_name="${MODEL_SHORT_NAMES[$model]}"
  flag=$(echo "$short_name" | tr '[:lower:]' '[:upper:]')
  
  cat >> "$OUTPUT_FILE" <<EOF
#ifdef USE_${flag}
   if (trim(model_names(model_idx)) == '${short_name}') then
      call ${short_name}_init_conditions(x(start_idx:end_idx))
      if (.not. time_set) then
         call ${short_name}_init_time(initial_time)
         time_set = .true.
      endif
   endif
#endif
EOF
done

cat >> "$OUTPUT_FILE" <<'EOF'
enddo

end subroutine get_initial_condition

!======================================================================

subroutine end_assim_model()
!--------------------------------------------------------------------
! Closes down assim_model - calls end_model for each component
!--------------------------------------------------------------------

EOF

# Generate end_model calls
for model in "${MODELS[@]}"; do
  short_name="${MODEL_SHORT_NAMES[$model]}"
  flag=$(echo "$short_name" | tr '[:lower:]' '[:upper:]')
  cat >> "$OUTPUT_FILE" <<EOF
#ifdef USE_${flag}
call ${short_name}_end_model()
#endif
EOF
done

cat >> "$OUTPUT_FILE" <<'EOF'

if (allocated(model_sizes)) deallocate(model_sizes)
if (allocated(model_offsets)) deallocate(model_offsets)
if (allocated(model_names)) deallocate(model_names)

end subroutine end_assim_model

!======================================================================
! Stub implementations for routines that need more complex handling
! These are placeholders that should be expanded based on requirements
!======================================================================

subroutine adv_1step(x, time)
!----------------------------------------------------------------------
real(r8),        intent(inout) :: x(:)
type(time_type), intent(in)    :: time

call error_handler(E_ERR, 'adv_1step', &
     'Multi-model advance not yet implemented', source, revision, revdate)

end subroutine adv_1step

!======================================================================

subroutine interpolate(state_handle, ens_size, location, obs_type, expected_obs, istatus)
!----------------------------------------------------------------------
use ensemble_manager_mod, only : ensemble_type
integer,             intent(in) :: ens_size
type(ensemble_type), intent(in) :: state_handle
type(location_type), intent(in) :: location
integer,             intent(in) :: obs_type
real(r8),           intent(out) :: expected_obs(ens_size)
integer,            intent(out) :: istatus(ens_size)

call error_handler(E_ERR, 'interpolate', &
     'Multi-model interpolation not yet implemented', source, revision, revdate)

end subroutine interpolate

!======================================================================

subroutine pert_model_copies(state_ens_handle, ens_size, pert_amp, interf_provided)
!----------------------------------------------------------------------  
use ensemble_manager_mod, only : ensemble_type
type(ensemble_type), intent(inout) :: state_ens_handle
integer,             intent(in)    :: ens_size
real(r8),            intent(in)    :: pert_amp
logical,             intent(out)   :: interf_provided

call error_handler(E_ERR, 'pert_model_copies', &
     'Multi-model perturbation not yet implemented', source, revision, revdate)

end subroutine pert_model_copies

!======================================================================

subroutine get_close_obs(gc, base_loc, base_type, locs, qtys, types, num_close, &
                         close_ind, distances, state_handle)
!----------------------------------------------------------------------
use location_mod, only : get_close_type
use ensemble_manager_mod, only : ensemble_type

type(get_close_type),          intent(in)    :: gc
type(location_type),           intent(inout) :: base_loc
integer,                       intent(in)    :: base_type
type(location_type),           intent(inout) :: locs(:)
integer,                       intent(in)    :: qtys(:)
integer,                       intent(in)    :: types(:)
integer,                       intent(out)   :: num_close
integer,                       intent(out)   :: close_ind(:)
real(r8),            optional, intent(out)   :: distances(:)
type(ensemble_type), optional, intent(in)    :: state_handle

call error_handler(E_ERR, 'get_close_obs', &
     'Multi-model get_close_obs not yet implemented', source, revision, revdate)

end subroutine get_close_obs

!======================================================================

subroutine get_close_state(gc, base_loc, base_type, locs, qtys, indx, num_close, &
                          close_ind, distances, state_handle)
!----------------------------------------------------------------------
use location_mod, only : get_close_type
use ensemble_manager_mod, only : ensemble_type

type(get_close_type),          intent(in)    :: gc
type(location_type),           intent(inout) :: base_loc
integer,                       intent(in)    :: base_type
type(location_type),           intent(inout) :: locs(:)
integer,                       intent(in)    :: qtys(:)
integer(i8),                   intent(in)    :: indx(:)
integer,                       intent(out)   :: num_close
integer,                       intent(out)   :: close_ind(:)
real(r8),            optional, intent(out)   :: distances(:)
type(ensemble_type), optional, intent(in)    :: state_handle

call error_handler(E_ERR, 'get_close_state', &
     'Multi-model get_close_state not yet implemented', source, revision, revdate)

end subroutine get_close_state

!======================================================================

subroutine convert_vertical_obs(ens_handle, num, locs, loc_qtys, loc_types, &
                                which_vert, status)
!----------------------------------------------------------------------
use ensemble_manager_mod, only : ensemble_type
type(ensemble_type), intent(in)    :: ens_handle
integer,             intent(in)    :: num
type(location_type), intent(inout) :: locs(:)
integer,             intent(in)    :: loc_qtys(:)
integer,             intent(in)    :: loc_types(:)
integer,             intent(in)    :: which_vert
integer,             intent(out)   :: status(:)

call error_handler(E_ERR, 'convert_vertical_obs', &
     'Multi-model vertical conversion not yet implemented', source, revision, revdate)

end subroutine convert_vertical_obs

!======================================================================

subroutine convert_vertical_state(ens_handle, num, locs, loc_qtys, loc_indx, &
                                  which_vert, status)
!----------------------------------------------------------------------
use ensemble_manager_mod, only : ensemble_type
type(ensemble_type), intent(in)    :: ens_handle
integer,             intent(in)    :: num
type(location_type), intent(inout) :: locs(num)
integer,             intent(in)    :: loc_qtys(num)
integer(i8),         intent(in)    :: loc_indx(num)
integer,             intent(in)    :: which_vert
integer,             intent(out)   :: status

call error_handler(E_ERR, 'convert_vertical_state', &
     'Multi-model vertical conversion not yet implemented', source, revision, revdate)

end subroutine convert_vertical_state

!======================================================================

function read_model_time(filename)
!----------------------------------------------------------------------
character(len=*),  intent(in)  :: filename
type(time_type)                :: read_model_time

! For now, read from first model
EOF

# Use first model for read_model_time
first_model=1
for model in "${MODELS[@]}"; do
  if [ $first_model -eq 1 ]; then
    short_name="${MODEL_SHORT_NAMES[$model]}"
    flag=$(echo "$short_name" | tr '[:lower:]' '[:upper:]')
    cat >> "$OUTPUT_FILE" <<EOF
#ifdef USE_${flag}
read_model_time = ${short_name}_read_model_time(filename)
return
#endif
EOF
    first_model=0
  fi
done

cat >> "$OUTPUT_FILE" <<'EOF'

call error_handler(E_ERR, 'read_model_time', &
     'No models available', source, revision, revdate)

end function read_model_time

!======================================================================

subroutine write_model_time(ncid, model_time)
!----------------------------------------------------------------------
integer,         intent(in) :: ncid
type(time_type), intent(in) :: model_time

! For now, write from first model
EOF

# Use first model for write_model_time
first_model=1
for model in "${MODELS[@]}"; do
  if [ $first_model -eq 1 ]; then
    short_name="${MODEL_SHORT_NAMES[$model]}"
    flag=$(echo "$short_name" | tr '[:lower:]' '[:upper:]')
    cat >> "$OUTPUT_FILE" <<EOF
#ifdef USE_${flag}
call ${short_name}_write_model_time(ncid, model_time, adv_to_time)
return
#endif
EOF
    first_model=0
  fi
done

cat >> "$OUTPUT_FILE" <<'EOF'

call error_handler(E_ERR, 'write_model_time', &
     'No models available', source, revision, revdate)

end subroutine write_model_time

!======================================================================

end module assim_model_mod
EOF

echo "Generated: $OUTPUT_FILE"
echo "Models included: ${MODELS[@]}"
