! DART software - Copyright UCAR. This open source software is provided
! by UCAR, "as is", without charge, subject to all terms of use at
! http://www.image.ucar.edu/DAReS/DART/DART_download

!> Multi-model version of assim_model_mod
!> This module wraps multiple model_mod modules to support 
!> assimilation with multiple models in a single executable.
!>
!> The MODELS to include are specified via preprocessor directives.
!> This file should be compiled after preprocessing model_mod.f90 files
!> from each model with model-specific prefixes.

module assim_model_mod

use    types_mod, only : r8

use time_manager_mod, only : time_type,                                            &
                             operator(<), operator(>), operator(+), operator(-),   &
                             operator(/), operator(*), operator(==), operator(/=)

use ensemble_manager_mod, only : ensemble_type

! Import the renamed model_mod modules
! These will be generated by preprocessing the original model_mod.f90 files
#ifdef USE_CAMFV
use camfv_model_mod, only : &
    camfv_get_model_size            => get_model_size, &
    camfv_static_init_model         => static_init_model, &
    camfv_get_state_meta_data       => get_state_meta_data, &
    camfv_shortest_time_between_assimilations => shortest_time_between_assimilations, &
    camfv_init_conditions           => init_conditions, &
    camfv_init_time                 => init_time, &
    camfv_adv_1step                 => adv_1step, &
    camfv_end_model                 => end_model, &
    camfv_pert_model_copies         => pert_model_copies, &
    camfv_get_close_obs             => get_close_obs, &
    camfv_get_close_state           => get_close_state, &
    camfv_convert_vertical_obs      => convert_vertical_obs, &
    camfv_convert_vertical_state    => convert_vertical_state, &
    camfv_model_interpolate         => model_interpolate, &
    camfv_read_model_time           => read_model_time, &
    camfv_write_model_time          => write_model_time
#endif

#ifdef USE_WRF
use wrf_model_mod, only : &
    wrf_get_model_size              => get_model_size, &
    wrf_static_init_model           => static_init_model, &
    wrf_get_state_meta_data         => get_state_meta_data, &
    wrf_shortest_time_between_assimilations => shortest_time_between_assimilations, &
    wrf_init_conditions             => init_conditions, &
    wrf_init_time                   => init_time, &
    wrf_adv_1step                   => adv_1step, &
    wrf_end_model                   => end_model, &
    wrf_pert_model_copies           => pert_model_copies, &
    wrf_get_close_obs               => get_close_obs, &
    wrf_get_close_state             => get_close_state, &
    wrf_convert_vertical_obs        => convert_vertical_obs, &
    wrf_convert_vertical_state      => convert_vertical_state, &
    wrf_model_interpolate           => model_interpolate, &
    wrf_read_model_time             => read_model_time, &
    wrf_write_model_time            => write_model_time
#endif

use utilities_mod, only : register_module, error_handler, E_ERR, E_MSG

use location_mod, only : location_type

implicit none
private

public :: static_init_assim_model, &
          end_assim_model, &
          get_initial_condition, &
          get_closest_state_time_to, &
          get_state_meta_data, &
          get_model_time_step, &
          get_model_size,  &
          adv_1step, &
          interpolate, &
          pert_model_copies, &
          get_close_obs, &
          get_close_state, &
          convert_vertical_obs, &
          convert_vertical_state, &
          read_model_time, &
          write_model_time

! Ensure init code is called exactly once
logical :: module_initialized = .false.

! Model size tracking
integer :: num_models
integer, allocatable :: model_sizes(:)
integer, allocatable :: model_offsets(:)  ! Starting index for each model in state vector
integer :: total_model_size

! Model names for identification
character(len=32), allocatable :: model_names(:)

! version controlled file description
character(len=*), parameter :: source   = 'xmodel/assim_model_mod.f90'
character(len=*), parameter :: revision = ''
character(len=*), parameter :: revdate  = ''

!-------------------------------------------------------------

contains

!======================================================================

subroutine static_init_assim_model()
!----------------------------------------------------------------------
! Initializes the multi-model assim_model
! Calls static_init_model for each component model
!----------------------------------------------------------------------

integer :: i, model_idx

! only execute this code once, even if called multiple times.
if (module_initialized) return

call register_module(source, revision, revdate)

module_initialized = .true.

! Count how many models are enabled
num_models = 0
#ifdef USE_CAMFV
num_models = num_models + 1
#endif
#ifdef USE_WRF
num_models = num_models + 1
#endif

if (num_models == 0) then
   call error_handler(E_ERR, 'static_init_assim_model', &
        'No models enabled. Define at least one USE_* preprocessor flag', &
        source, revision, revdate)
endif

allocate(model_sizes(num_models))
allocate(model_offsets(num_models))
allocate(model_names(num_models))

! Initialize each model and get its size
model_idx = 0
total_model_size = 0

#ifdef USE_CAMFV
model_idx = model_idx + 1
model_names(model_idx) = 'camfv'
call camfv_static_init_model()
model_sizes(model_idx) = camfv_get_model_size()
model_offsets(model_idx) = total_model_size + 1
total_model_size = total_model_size + model_sizes(model_idx)
write(*, *) 'Model ', model_idx, ': ', trim(model_names(model_idx)), &
            ' Size: ', model_sizes(model_idx), ' Offset: ', model_offsets(model_idx)
#endif

#ifdef USE_WRF
model_idx = model_idx + 1
model_names(model_idx) = 'wrf'
call wrf_static_init_model()
model_sizes(model_idx) = wrf_get_model_size()
model_offsets(model_idx) = total_model_size + 1
total_model_size = total_model_size + model_sizes(model_idx)
write(*, *) 'Model ', model_idx, ': ', trim(model_names(model_idx)), &
            ' Size: ', model_sizes(model_idx), ' Offset: ', model_offsets(model_idx)
#endif

write(*, *) 'Multi-model initialization complete'
write(*, *) 'Number of models: ', num_models
write(*, *) 'Total state size: ', total_model_size

end subroutine static_init_assim_model

!======================================================================

function get_model_size()
!----------------------------------------------------------------------
! Returns the size of the combined model state
!----------------------------------------------------------------------

integer :: get_model_size

get_model_size = total_model_size

end function get_model_size

!======================================================================

subroutine get_state_meta_data(index_in, location, var_type)
!----------------------------------------------------------------------
! Returns the location and type of a state variable
! Determines which model owns this index and calls appropriate routine
!----------------------------------------------------------------------

integer(i8),         intent(in)  :: index_in
type(location_type), intent(out) :: location
integer,             intent(out) :: var_type

integer :: model_idx, local_index

! Find which model owns this state index
call find_model_for_index(index_in, model_idx, local_index)

! Call the appropriate model's get_state_meta_data
select case (model_idx)
#ifdef USE_CAMFV
   case (1)  ! Assuming camfv is model 1 if defined
      call camfv_get_state_meta_data(local_index, location, var_type)
#endif
#ifdef USE_WRF
   case (2)  ! Assuming wrf is model 2 if both defined, or 1 if only wrf
      call wrf_get_state_meta_data(local_index, location, var_type)
#endif
   case default
      call error_handler(E_ERR, 'get_state_meta_data', &
           'Invalid model index', source, revision, revdate)
end select

end subroutine get_state_meta_data

!======================================================================

function get_model_time_step()
!----------------------------------------------------------------------
! Returns the shortest time step from all models
!----------------------------------------------------------------------

type(time_type) :: get_model_time_step
type(time_type) :: model_time_step

#ifdef USE_CAMFV
get_model_time_step = camfv_shortest_time_between_assimilations()
#endif

#ifdef USE_WRF
model_time_step = wrf_shortest_time_between_assimilations()
#ifdef USE_CAMFV
if (model_time_step < get_model_time_step) then
   get_model_time_step = model_time_step
endif
#else
get_model_time_step = model_time_step
#endif
#endif

end function get_model_time_step

!======================================================================

function get_closest_state_time_to(model_time, given_time)
!----------------------------------------------------------------------
! Returns the time closest to the given time that the model can reach
!----------------------------------------------------------------------

type(time_type) :: get_closest_state_time_to
type(time_type), intent(in) :: model_time, given_time

type(time_type) :: time_step

time_step = get_model_time_step()

if(model_time > given_time) then
   get_closest_state_time_to = model_time
   return
endif

get_closest_state_time_to = model_time

do while((time_step + 2*get_closest_state_time_to) < 2*given_time)
   get_closest_state_time_to = get_closest_state_time_to + time_step
enddo

end function get_closest_state_time_to

!======================================================================

subroutine get_initial_condition(initial_time, x)
!----------------------------------------------------------------------
! Get initial conditions for all models
!----------------------------------------------------------------------

type(time_type), intent(out) :: initial_time
real(r8),        intent(out) :: x(:)

integer :: model_idx, start_idx, end_idx

! Get initial conditions from each model
#ifdef USE_CAMFV
start_idx = model_offsets(1)
end_idx = start_idx + model_sizes(1) - 1
call camfv_init_conditions(x(start_idx:end_idx))
call camfv_init_time(initial_time)
#endif

#ifdef USE_WRF
! Find WRF model index based on what's defined
#ifdef USE_CAMFV
model_idx = 2
#else
model_idx = 1
#endif
start_idx = model_offsets(model_idx)
end_idx = start_idx + model_sizes(model_idx) - 1
call wrf_init_conditions(x(start_idx:end_idx))
! Override time if WRF time is earlier? For now just use first model's time
#endif

end subroutine get_initial_condition

!======================================================================

subroutine end_assim_model()
!--------------------------------------------------------------------
! Closes down assim_model - calls end_model for each component
!--------------------------------------------------------------------

#ifdef USE_CAMFV
call camfv_end_model()
#endif

#ifdef USE_WRF
call wrf_end_model()
#endif

if (allocated(model_sizes)) deallocate(model_sizes)
if (allocated(model_offsets)) deallocate(model_offsets)
if (allocated(model_names)) deallocate(model_names)

end subroutine end_assim_model

!======================================================================
! Helper routines
!======================================================================

subroutine find_model_for_index(index_in, model_idx, local_index)
!----------------------------------------------------------------------
! Determines which model owns a given state index
! Returns the model index and the local index within that model
!----------------------------------------------------------------------

integer(i8), intent(in)  :: index_in
integer,     intent(out) :: model_idx
integer(i8), intent(out) :: local_index

integer :: i

do i = 1, num_models
   if (index_in >= model_offsets(i) .and. &
       index_in < model_offsets(i) + model_sizes(i)) then
      model_idx = i
      local_index = index_in - model_offsets(i) + 1
      return
   endif
enddo

call error_handler(E_ERR, 'find_model_for_index', &
     'Index not found in any model', source, revision, revdate)

end subroutine find_model_for_index

!======================================================================
! Stub implementations for routines that need more complex handling
! These are placeholders that should be expanded based on requirements
!======================================================================

subroutine adv_1step(x, time)
!----------------------------------------------------------------------
real(r8),        intent(inout) :: x(:)
type(time_type), intent(in)    :: time

call error_handler(E_ERR, 'adv_1step', &
     'Multi-model advance not yet implemented', source, revision, revdate)

end subroutine adv_1step

!======================================================================

subroutine interpolate(state_handle, ens_size, location, obs_type, expected_obs, istatus)
!----------------------------------------------------------------------
use ensemble_manager_mod, only : ensemble_type
integer,             intent(in) :: ens_size
type(ensemble_type), intent(in) :: state_handle
type(location_type), intent(in) :: location
integer,             intent(in) :: obs_type
real(r8),           intent(out) :: expected_obs(ens_size)
integer,            intent(out) :: istatus(ens_size)

call error_handler(E_ERR, 'interpolate', &
     'Multi-model interpolation not yet implemented', source, revision, revdate)

end subroutine interpolate

!======================================================================

subroutine pert_model_copies(state_ens_handle, ens_size, pert_amp, interf_provided)
!----------------------------------------------------------------------  
use ensemble_manager_mod, only : ensemble_type
type(ensemble_type), intent(inout) :: state_ens_handle
integer,             intent(in)    :: ens_size
real(r8),            intent(in)    :: pert_amp
logical,             intent(out)   :: interf_provided

call error_handler(E_ERR, 'pert_model_copies', &
     'Multi-model perturbation not yet implemented', source, revision, revdate)

end subroutine pert_model_copies

!======================================================================

subroutine get_close_obs(gc, base_loc, base_type, locs, kinds, num_close, &
                         close_ind, distances, state_handle)
!----------------------------------------------------------------------
use location_mod, only : get_close_type
use ensemble_manager_mod, only : ensemble_type

type(get_close_type),          intent(in)    :: gc
type(location_type),           intent(inout) :: base_loc
integer,                       intent(in)    :: base_type
type(location_type),           intent(inout) :: locs(:)
integer,                       intent(in)    :: kinds(:)
integer,                       intent(out)   :: num_close
integer,                       intent(out)   :: close_ind(:)
real(r8),            optional, intent(out)   :: distances(:)
type(ensemble_type), optional, intent(in)    :: state_handle

call error_handler(E_ERR, 'get_close_obs', &
     'Multi-model get_close_obs not yet implemented', source, revision, revdate)

end subroutine get_close_obs

!======================================================================

subroutine get_close_state(gc, base_loc, base_type, locs, kinds, num_close, &
                          close_ind, distances, state_handle)
!----------------------------------------------------------------------
use location_mod, only : get_close_type
use ensemble_manager_mod, only : ensemble_type

type(get_close_type),          intent(in)    :: gc
type(location_type),           intent(inout) :: base_loc
integer,                       intent(in)    :: base_type
type(location_type),           intent(inout) :: locs(:)
integer,                       intent(in)    :: kinds(:)
integer,                       intent(out)   :: num_close
integer,                       intent(out)   :: close_ind(:)
real(r8),            optional, intent(out)   :: distances(:)
type(ensemble_type), optional, intent(in)    :: state_handle

call error_handler(E_ERR, 'get_close_state', &
     'Multi-model get_close_state not yet implemented', source, revision, revdate)

end subroutine get_close_state

!======================================================================

subroutine convert_vertical_obs(ens_handle, num, locs, loc_qtys, loc_types, &
                                which_vert, status)
!----------------------------------------------------------------------
use ensemble_manager_mod, only : ensemble_type
type(ensemble_type), intent(in)    :: ens_handle
integer,             intent(in)    :: num
type(location_type), intent(inout) :: locs(:)
integer,             intent(in)    :: loc_qtys(:)
integer,             intent(in)    :: loc_types(:)
integer,             intent(in)    :: which_vert
integer,             intent(out)   :: status(:)

call error_handler(E_ERR, 'convert_vertical_obs', &
     'Multi-model vertical conversion not yet implemented', source, revision, revdate)

end subroutine convert_vertical_obs

!======================================================================

subroutine convert_vertical_state(ens_handle, num, locs, loc_qtys, loc_indx, &
                                  which_vert, status)
!----------------------------------------------------------------------
use ensemble_manager_mod, only : ensemble_type
type(ensemble_type), intent(in)    :: ens_handle
integer,             intent(in)    :: num
type(location_type), intent(inout) :: locs(:)
integer,             intent(in)    :: loc_qtys(:)
integer(i8),         intent(in)    :: loc_indx(:)
integer,             intent(in)    :: which_vert
integer,             intent(out)   :: status(:)

call error_handler(E_ERR, 'convert_vertical_state', &
     'Multi-model vertical conversion not yet implemented', source, revision, revdate)

end subroutine convert_vertical_state

!======================================================================

subroutine read_model_time(filename, model_time)
!----------------------------------------------------------------------
character(len=*),  intent(in)  :: filename
type(time_type),   intent(out) :: model_time

! For now, read from first model
#ifdef USE_CAMFV
call camfv_read_model_time(filename, model_time)
#elif defined USE_WRF
call wrf_read_model_time(filename, model_time)
#endif

end subroutine read_model_time

!======================================================================

subroutine write_model_time(ncid, model_time, adv_to_time)
!----------------------------------------------------------------------
integer,         intent(in) :: ncid
type(time_type), intent(in) :: model_time
type(time_type), intent(in) :: adv_to_time

! For now, write from first model
#ifdef USE_CAMFV
call camfv_write_model_time(ncid, model_time, adv_to_time)
#elif defined USE_WRF
call wrf_write_model_time(ncid, model_time, adv_to_time)
#endif

end subroutine write_model_time

!======================================================================

end module assim_model_mod
