name: Test Github Actions Dynamic Matrix
on:
  workflow_dispatch:
  
jobs:
  setup:
    runs-on: ubuntu-latest
    # Deploy container on top of runner instance
    container: 
      image: hkershaw/dart-dep:1.0
      options: "--cap-add=SYS_PTRACE"    
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - uses: actions/checkout@v4
      - id: matrix
        run: |
          git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
          DART=$(git rev-parse --show-toplevel)
          files_to_process=( $(find $DART -executable -type f -name quickbuild.sh | sed -E 's#(\./|quickbuild\.sh)##g') )
          joined_items=""
          for item in "${files_to_process[@]}"; do
            # Append the quoted item and a comma to the string
            echo $item
            stripped_item=${item#/__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}}  # removes /__w/DART/DART
            joined_items+="\"$stripped_item\","
          done

          # Remove the trailing comma from the last item
          joined_items="${joined_items%,}"

          echo "value=[ $joined_items ]" >> $GITHUB_OUTPUT
        shell: bash
      - run: |
          echo "${{ steps.matrix.outputs.value }}"
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJSON(needs.setup.outputs.matrix)}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set checked out repo as a safe git directory
        run: git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
      - name: Creating Makefile template
        run: |
          cd build_templates
          cp mkmf.template.gfortran mkmf.template
          echo 'FFLAGS = -g -Wuninitialized -Wunused -ffree-line-length-none -fbounds-check -fbacktrace -ffpe-trap=invalid,zero,overflow $(INCS)' >> mkmf.template
        shell: bash
      - name: Run quickbuild.sh script
        run: |
          cd ${{ matrix.value }}
          ./quickbuild.sh
        shell: bash
