name: Test Github Actions Dynamic Matrix
on:
  workflow_dispatch:
  
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - uses: actions/checkout@v4
      - id: matrix
        run: |
          files_to_process=( $(find $GITHUB_WORKSPACE -executable -type f -name quickbuild.sh | sed -E 's#(\./|quickbuild\.sh)##g') )
          echo "value=$(printf '[ %s ]\n' "$(IFS=,; printf '\"%s\"' "${files_to_process[@]}")" | jq -R . | jq -s .)" >> $GITHUB_OUTPUT
      - run: |
          echo "${{ steps.matrix.outputs.value }}"
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJSON(needs.setup.outputs.matrix)}}
    steps:
      - run: |
          echo "${{ matrix.value }}"
