name: Test Github Actions Dynamic Matrix
on:
  workflow_dispatch:
  
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - uses: actions/checkout@v4
      - id: matrix
        run: |
          files_to_process=( $(find $GITHUB_WORKSPACE -executable -type f -name quickbuild.sh | sed -E 's#(\./|quickbuild\.sh)##g') )
          joined_items=""
          for item in "${files_to_process[@]}"; do
            # Append the quoted item and a comma to the string
            echo $item
            joined_items+="\"$item\","
          done

          # Remove the trailing comma from the last item
          joined_items="${joined_items%,}"

          echo "value=[ $joined_items ]" >> $GITHUB_OUTPUT
          #echo "value=[\"/home/runner/work/DART/DART/developer_tests/preprocess/work/\"]" >> $GITHUB_OUTPUT
      - run: |
          echo "${{ steps.matrix.outputs.value }}"
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJSON(needs.setup.outputs.matrix)}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set checked out repo as a safe git directory
        run: git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
      - name: Run quickbuild.sh script
        run: |
          cd ${{ matrix.value }}
          ./quickbuild.sh
